### ISSUE TITLE
Cops Isn't Go-Get-Able

### ISSUE THREAD

**Issue by jcorbin** [kriskowal/cops#1]
Your lack of toplevel `.go` files causes `go get github.com/kriskowal/cops` to bail with:
```
package github.com/kriskowal/cops: no Go files in $GOPATH/src/github.com/kriskowal/cops
```

I'd suggest starting with a `doc.go`, which is a good segue into writing any of your missing doc strings ;-)

**Comment by jcorbin** [comment]
Of course there's the larger question "why don't you have a toplevel API? what should it be? Corollary: are you really sure you want to be exporting all of the sub-packages you have now, or should things like `vtcolor` really be `cops/internal/vtcolor`?

**Comment by jcorbin** [comment]
Fixed now; got me some cops!

**Comment by kriskowal** [comment]
Added a doc.go. I may use the top-level package for shared interfaces.

I’ve documented the API. I’m generally content with the organization and developer experience, but it is possible that merging some of the subpackages would make usage simpler. I could see folding vtcolor into display, since the color models are a required argument of Render.

I could see folding cursor back into display, but I prefer to have one New() per package generally.

I like having a separate `text` package. I hope to eventually add `vttext`, the more involved implementation of the same interface.

Ideas welcome.
